name: ui_components
description: "A new Flutter project containing customized components."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.5
  flutter_pdfview: ^1.4.0
  uuid: ^4.5.1
  file_picker: ^8.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  pinput: ^5.0.1
  youtube_player_iframe: ^5.2.1
  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true